### ISSUE TITLE
Aid All

### ISSUE THREAD

**Issue by TemhAAhmeT** [Th3C0D3R/FoBJS_Release#10]
Helping Friends, all, etc. throws an error:

i18n is not defined

I tried language de and en, both same.
aid, tavern doesnt work on my side which both working 1 previous version.

**Comment by Th3C0D3R** [comment]
Download again, there was an error

**Comment by Th3C0D3R** [comment]
Does it work now?

**Comment by TemhAAhmeT** [comment]
Yep, all working good.
Thanks
