### ISSUE TITLE
Bot is going to be broken

### ISSUE THREAD

**Issue by IIMugi** [Th3C0D3R/FoBJS_Release#15]
Sir i am using your bot. But when i use the bot after 3 days bot was going broken. When i tried to open it always error,  I think it's about json files but i dont understand the situation. Can you check. Sorry for my bad english.

**Comment by Th3C0D3R** [comment]
Can you show me the error? 
Also I am currently working on a better version of the Bot but will take a while

**Comment by IIMugi** [comment]
Yes sir,

After 2 days use. https://prnt.sc/rbw95e

**Comment by Th3C0D3R** [comment]
do you use the ProductionBot to selfcollect and start productions?

maybe you can run the bot from terminal (command line), it will then print some stuff.
As soon as you get the error can you then please show me the terminal output?

also try to clear your user data and login again. the bot will stop working if there is a new version and you havent restart it. sadly, this can only be fixed by restarting and relogin again

**Comment by IIMugi** [comment]
yes sir i was using the ProductionBot for collecting. For auto of course. 

I dont know how to use terminal (is there any faq) ? I dont have enough information about the coding :( Btw i deleted all data and files. But it never opens. I need to do format my PC.

**Comment by Th3C0D3R** [comment]
> 
> 
> yes sir i was using the ProductionBot for collecting. For auto of course.
> 
> I dont know how to use terminal (is there any faq) ? I dont have enough information about the coding :( Btw i deleted all data and files. But it never opens. I need to do format my PC.

No, dont have to format PC

Maybe re-download the bot and try again. you should not delete anything inside the Bot folder.

To run it with terminal open the command line (press "Windows"-key and then "R" -> opens a "Run" box -> enter "cmd" -> and go into the folder where you have the bot (for your example enter: "cd C:/Users/Administator/Downloads/fobjs_windows/fobjs-win32-x64/" (without ") -> press enter -> enter "fobjs.exe" -> press enter

**Comment by IIMugi** [comment]
Sir i deleted all files. And downloaded again.  I tried to use on CMD. but it is same error. 

https://prnt.sc/rbxdq i tried on my pc and RDP. After 2 days use, both of them occured same error.

**Comment by Th3C0D3R** [comment]
please do the following:
"Windows"-key and then "R" -> opens a "Run" box -> enter "%appdata%" hit enter -> navigate to the "Forge of Bots JS" Folder and delete the following files: please delete all .json files inside the folder

**Comment by IIMugi** [comment]
Sir,

I deleted all .json on the appdata. The problem is solved thanks to you. Thank you very much. When will you publish new one :)

**Comment by Th3C0D3R** [comment]
I am currently working on a improved version of the bot written in C# which will significantly boost up the performance.
also the Ui Logic is easier to handle then.
But this could take a while

**Comment by IIMugi** [comment]
i look forward to see it 👍 you are great person thanks :)))))
