### ISSUE TITLE
Beta v1.2.3 does not login - just has a blank screen

### ISSUE THREAD

**Issue by ajschroeder** [Th3C0D3R/FoBJS_Release#18]
Trying to login to the US servers with the bot. The bot asks for username and password, which I enter. Then the bot shows me the list of the worlds that I belong to, when I enter the world and press enter there is a popup window that opens and closes right away, and then the main window for the bot sits there with no output on the screen.

I am running this on Windows 10 Home version 1909. Please let me know if you need anything else.

**Comment by Th3C0D3R** [comment]
Can you take a screen with the console output after you run it through the console

**Comment by ajschroeder** [comment]
Sure, here it is after logging out, then logging in and selecting the FOE world:

![Screen Shot 2020-04-08 at 11 58 13 AM](https://user-images.githubusercontent.com/6432150/78812298-cbd1d780-7990-11ea-8ca5-3780b0006854.png)

**Comment by Th3C0D3R** [comment]
Oh I did not mean this console. Run the exe from the cmd in windown

**Comment by ajschroeder** [comment]
Oh ok, here is the info from the windows console:

![FOE-Bot-Console](https://user-images.githubusercontent.com/6432150/78813367-844c4b00-7992-11ea-9172-f2ed7a6f1d84.png)

**Comment by Th3C0D3R** [comment]
It looks like it can not login properly. Can you delete the User data (Settings -> Delete alls Data or how its called) and login again? If its still not working I currently cant do much because I am very busy with RL and other projects

**Comment by Kizala** [comment]
@ajschroeder  go to %appdata% and try to delete "Forge of Bots JS" Folder, then start FoB again

**Comment by ajschroeder** [comment]
@Kizala that worked! I am now able to login and have the bot do things. Thank you!

**Comment by Th3C0D3R** [comment]
@Kizala thank you for the help 😊
