### ISSUE TITLE
Unable to load overview

### ISSUE THREAD

**Issue by andrewcharlwood** [Th3C0D3R/FoBJS_Release#2]
Which Server are you playing on (de/en/beta(zz)/...) - en
What OS you run - Windows 10 Pro
Are there any errors on the screen - No
Expected behavior - After logging in and selecting the specific world, the program should proceed to an overview
Actual behavior - after selecting world (e.g. en5), the screen is black and blank, the app does connect to the internet as it has network activity, but nothing happens.

**Comment by Th3C0D3R** [comment]
Thank you for your report. its still in An early dev-state and could contain bugs

Can you please do the same procedure again but before doing something, open the DevTools?
so first after open the program, got to settings -> Clear Userdata and then Click on DevTools
And when it goes black -> see if there are errors (red) in the console and report again

Also please input the Username and password correctly because You wouldn't get an error if they are incorrect 

I will make a Video next Week so it can be clear for everyone how it should Look

**Comment by Th3C0D3R** [comment]
Also if you have the DevTools open,
Please input each of these and copy each output for me:
UserIDs.UID
UserIDs.WID
UserIDs.ForgeHX

And maybe I already encountered the Issue, but have to test it

**Comment by Th3C0D3R** [comment]
Found the problem.
New build is building right now.
Released within the next 2hours

**Comment by andrewcharlwood** [comment]
Sorry, not at home currently otherwise would have provided logs! 

Will give it a try when I'm back and let you know how it goes.

**Comment by Th3C0D3R** [comment]
Just use v1.2.0beta

**Comment by andrewcharlwood** [comment]
Have given it a couple of goes with no, luck, unfortunately.

I know logging in must work, as it kicks me out of any other instances i'm logged into (e.g. my phone or a browser)

> Can you please do the same procedure again but before doing something, open the DevTools?
so first after open the program, got to settings -> Clear Userdata and then Click on DevTools
And when it goes black -> see if there are errors (red) in the console and report again

After doing the above I have no red errors, just amber:

> A cookie associated with a cross-site resource at http://forgeofempires.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
login.html:1 A cookie associated with a cross-site resource at https://en5.forgeofempires.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.




Do you want me to run anything in the console?

**Comment by Th3C0D3R** [comment]
Do you use the newest version?

**Comment by Th3C0D3R** [comment]
Also try to run the exe from commandline

It will output stuff like CSRF etc, this can you post. If there is nothing I think its the older version

**Comment by andrewcharlwood** [comment]
> Also try to run the exe from commandline
> 
> It will output stuff like CSRF etc, this can you post. If there is nothing I think its the older version

Will do,

Deffo new version, says 1.2.0 at the top

**Comment by andrewcharlwood** [comment]
Ran from command line, on loading exe I get

`(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
XSRF (p2Qaj_QPVUgBGyOxQfm53qXkRhHOK4_AE_dp8z6LFFA) loaded
CID (171922321) loaded
CSRF (VpFVuUFiMQAF_OXzzPdDqK1B5Lkz1YyP7BPyI0jv32jjnIQrDZs6j5EKykoclph5) loaded
CID (1196235474) loaded
SID (pIuTBVEG8Gp9C8ZZh1oAGbLyWQ-4oTRJtdWw4_zL) loaded
WID (en5) loaded
(node:3992) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at downloadForgeHX (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:234:25)
    at EventEmitter.<anonymous> (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:338:13)
    at EventEmitter.emit (events.js:210:5)
    at C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\module\FoBProxy.js:62:39
(node:3992) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at downloadForgeHX (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:234:25)
    at EventEmitter.<anonymous> (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:338:13)
    at EventEmitter.emit (events.js:210:5)
    at C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\module\FoBProxy.js:62:39
(node:3992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

After typing "Login" i, I am not asked for my username, the screen goes black, the following is on the command line:

`XSRF (p2Qaj_QPVUgBGyOxQfm53qXkRhHOK4_AE_dp8z6LFFA) loaded
CID (171922321) loaded
CSRF (VpFVuUFiMQAF_OXzzPdDqK1B5Lkz1YyP7BPyI0jv32jjnIQrDZs6j5EKykoclph5) loaded
CID (1196235474) loaded
SID (pIuTBVEG8Gp9C8ZZh1oAGbLyWQ-4oTRJtdWw4_zL) loaded
WID (en5) loaded
(node:3992) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at downloadForgeHX (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:234:25)
    at EventEmitter.<anonymous> (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:338:13)
    at EventEmitter.emit (events.js:210:5)
    at C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\module\FoBProxy.js:62:39
(node:3992) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at downloadForgeHX (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:234:25)
    at EventEmitter.<anonymous> (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:338:13)
    at EventEmitter.emit (events.js:210:5)
    at C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\module\FoBProxy.js:62:39
(node:3992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Clicking "Login" on the bar works, asks my username and nothing in the command line.

Login with username/password, I get asked which world to login to, on the command line:

'CID (171922321) loaded'

After choosing the world I want to load the following is on the command line:

'CID (1196235474) loaded
SID (2Djf8gSd2KGrmCjIqz9-Q6Xn8By_YuPXE3PZ9m9Q) loaded'

The screen stays black with no text.

**Comment by andrewcharlwood** [comment]
I cleared everything through the menu, after selecting language server, I type Login, again, it doesn't work and  the screen goes black, but instead the following is on the command line:

>XSRF (3jnHu9bdI0OLvLXmm8sMfcfxUtfEd6313hBB1n4zoFo) loaded
CID (171922321) loaded
CSRF (n3SrY_K8vYc0cID5-Tvf3G4T1CpHs1C2VP70TNXVrnFuajw8BzFghb2tZCDDYBQb) loaded

**Comment by andrewcharlwood** [comment]
So, I ran the command prompt as an admin, no issues with login, as smooth as butter.

After choosing the world (e.g. en4), the screen stays black, but the following is in the command prompt:

C:\Users\Andy\Desktop\fobjs-win32-x64>
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
XSRF (xbOGS3vUeDN0tR0JjKcUBVkLPmRM_U7ITT6UmnYVjOA) loaded
CID (171922321) loaded
CSRF (Nw45l6CxT89OlLRy43vBFXlPZ3RGrRqjRpQc-SGshJzOWRyRJWRMXolRv2_Cyp0T) loaded
CID (1196235474) loaded
SID (aq3UHCBguj98KuJJOqLJcxCx1WZDXHsj65K_TDDP) loaded
WID (en5) loaded
(node:1392) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at downloadForgeHX (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:234:25)
    at EventEmitter.<anonymous> (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:338:13)
    at EventEmitter.emit (events.js:210:5)
    at C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\module\FoBProxy.js:62:39
(node:1392) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at downloadForgeHX (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:234:25)
    at EventEmitter.<anonymous> (C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\main.js:338:13)
    at EventEmitter.emit (events.js:210:5)
    at C:\Users\Andy\Desktop\fobjs-win32-x64\resources\app.asar\module\FoBProxy.js:62:39
(node:1392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andrewcharlwood** [comment]
![cmdline](https://user-images.githubusercontent.com/44037977/74590147-aaddad80-5003-11ea-9130-ff98b0a3d8a0.PNG)

Don't know if that's any easier to see, not sure the best way of formatting it above,

**Comment by Th3C0D3R** [comment]
Well, thanks. 
I could locate the source of the bug. Cant fix it right now

**Comment by andrewcharlwood** [comment]
> Well, thanks.
> I could locate the source of the bug. Cant fix it right now

No problem, happy to help! Let me know if you need me to test anything in the future :)

**Comment by Th3C0D3R** [comment]
> > Well, thanks.
> > I could locate the source of the bug. Cant fix it right now
> 
> No problem, happy to help! Thanks for making this. Let me know if you need me to test anything in the future :)

So after some investigation I found out that the source was not the problem. Because on my end everything is working (even with fresh installation.)

Can you look into the Appdata Folder if there is a file called: ForgeHX-xxxx.js (where x is a number or letter)
If so, please delete it.
Then start the programm again over the command line and clear the userdata again. copy the console output again. I hope I can fix it then...

**Comment by andrewcharlwood** [comment]
> > > Well, thanks.
> > > I could locate the source of the bug. Cant fix it right now
> > 
> > 
> > No problem, happy to help! Thanks for making this. Let me know if you need me to test anything in the future :)
> 
> So after some investigation I found out that the source was not the problem. Because on my end everything is working (even with fresh installation.)
> 
> Can you look into the Appdata Folder if there is a file called: ForgeHX-xxxx.js (where x is a number or letter)
> If so, please delete it.
> Then start the programm again over the command line and clear the userdata again. copy the console output again. I hope I can fix it then...

Hey,

Can't seem to find a file of that name anywhere on my system, or is it something in dev tools I need to be looking at?

**Comment by Th3C0D3R** [comment]
Thats just odd. I have to look into it. Could take a while.

**Comment by Th3C0D3R** [comment]
Soooo after some interesting things I got during testing I could not fix the behavior.
but I cleaned everything from my appdata folder related to the Bot and got it working.

so what you can try to do are these steps:

1. Open the exe
2. Go to the settings Menu and click: "clear Userdata" and after that "clear everything" now you should see the server selection.
3. Close the bot, go to the %appdata% folder and delete the ForgeHX-xxx.js (if its exists) and the Forge of Bots JS Folder completely.
4. Open the bot again (from command line) and again click "clear Userdata" and "clear everything)
5. now select server (en)
6. Now click Login (or enter it in the input field and press return)

If you have to enter username, go ahead.
please then report me back the cmd
Output if it does not work

**Comment by andrewcharlwood** [comment]
Success!

So, I followedc the steps above, I also used the tool Everything to find anything related to forge of empires in my PC and delete it to be safe (Still nothing called Forge HX though)

I booted up, after step 6, it didn't prompt me for my username.

I waited a little while, tried pressing & typing login again, and still nothing. So I closed the program and it spat out the following:

>C:\Users\Andy\Desktop\fobjs-win32-x64>
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
XSRF (Ew8pSdVIR7wpYHO8tkX8Kf4IfOAQj6KBeQjRp5qsNQU) loaded
CSRF (SicerZb4md4LMtb9frIbV_kmWn_PDSdQDIN7NQ53V6qMz6Za1Up0eLEHFJWSC-4j) loaded
(node:11432) UnhandledPromiseRejectionWarning: TypeError: Failed to fetch
(node:11432) UnhandledPromiseRejectionWarning: TypeError: Failed to fetch
(node:11432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11432) UnhandledPromiseRejectionWarning: TypeError: Failed to fetch
(node:11432) UnhandledPromiseRejectionWarning: TypeError: Failed to fetch
(node:11432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
XSRF (Ew8pSdVIR7wpYHO8tkX8Kf4IfOAQj6KBeQjRp5qsNQU) loaded



I then booted up from the command line again, I didn't clear anything I just typed login ( I noticed that even after closing the app a half dozen processes were still running)

Anyway, after rebooting and logging in, it worked perfectly!

>C:\Users\Andy\Desktop\fobjs-win32-x64>fobjs.exe
C:\Users\Andy\Desktop\fobjs-win32-x64>
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
XSRF (ob9N4jChMnRpSDYDsrLqnnVctGIMmjTOzXNUgUpyMuI) loaded
CSRF (SZrNJYrHXrhBdCj6s6EqhsiCI3KQKhLNxHL5PLPX_jernBG2vX4x_zB5uyB2clqn) loaded
CID (1956493653) loaded
CID (1282991567) loaded
SID (403AgsDfTBwG4WUopFvrTBdfXia0KacQdh9NOvvb) loaded
WID (en5) loaded
ForgeHX (ForgeHX-f0196d30.js) loaded

Thank you very much for your help! The program looks great and seems to be working perfectly.

**Comment by Th3C0D3R** [comment]
Thank you. Now it should work everytime you start it (i hope so)

The fact that multiple process could still be running did I forget

**Comment by andrewcharlwood** [comment]
One thing I noticed in the menu which I think has failed to translate is "Suche snippbare LGs", just thought i'd let you know!

**Comment by Th3C0D3R** [comment]
Yes it was a feature I added quickly to test it with the bot (so its not working like it should)

I am currently working on the translation of the bot.
