### ISSUE TITLE
Window always loads again

### ISSUE THREAD

**Issue by BreimmGer** [Th3C0D3R/FoBJS_Release#20]
Hi there,
When the bot picks up the supplies
Then the bot always reloads

Gruß Breimm

**Comment by Th3C0D3R** [comment]
Jap, das aktualisieren ist notwendig um die Oberfläche zu aktualisieren. konnte leider nicht besser gelöst werden.

**Comment by BreimmGer** [comment]
Hallo
Ja aber er macht es auch wenn es nichts holt

**Comment by Th3C0D3R** [comment]
Wie muss ich das verstehen?

**Comment by BreimmGer** [comment]
Ja 
Werde ein Video machen 😄

**Comment by BreimmGer** [comment]
Aber sehr gutes Programm 
Tolle Arbeit

**Comment by BreimmGer** [comment]
https://drive.google.com/open?id=1CgpCou9u6t7KarZivTAab5YPoua8K8Jq

**Comment by Th3C0D3R** [comment]
Starte den Bot nochmal neu, vielleicht ist da auch was schief gegangen

**Comment by BreimmGer** [comment]
Mach ich immer wieder 
Aber es kommt wieder oder mit Admin starten

**Comment by Th3C0D3R** [comment]
Mhm ist der Produktionbot an, das die Produktionen automatisch eingesammelt werden?
Wenn ja, den mal ausstellen

**Comment by BreimmGer** [comment]
Ja ist 
Mach ihn mal aus

**Comment by Th3C0D3R** [comment]
Man kann über ein klick dann alle Gebäude sammeln, leider manuell dann ja.
Dieser Bot funktioniert in dee von mir genutzten sprache und Framework (Javascript und ElectronJs) nicht wie gewünscht. 
Bin aktuell noch an anderen Projekten tätig als auch RL viel beschäftigt. Bei genug Zeit wird eine neue Version in anderer Programmiersprache verfügbare sein bzw weiterentwickelt welche dann besser funktionieren wird

**Comment by BreimmGer** [comment]
Ok danke für die Info

**Comment by BreimmGer** [comment]
Hallo Th3C0D3Rd
Läuft der Bot unter Linux Besser

**Comment by Th3C0D3R** [comment]
Konnte ich nicht testen, sollte aber gleich funktionieren.
Werd ich bei Gelegenheit mal testen

**Comment by BreimmGer** [comment]
![fehler](https://user-images.githubusercontent.com/63580780/79487486-97a58900-8018-11ea-8123-fb392d67d43d.jpg)
Hallo
Ich bekomme seit ebend eine fehler Meldung
Die Tage bis heute Mittag war alles ok

Gruß Breimm

**Comment by Th3C0D3R** [comment]
Geh in den %appdata% Ordner und versuch den "Forge of Bots JS" Ordner zu löschen (oder einer der so ähnlich heißt) musst dich dann neu anmelden. Bei mir gabs die Meldung nämlich nicht 😅 (gerade probiert)
Wenns nicht geht gib mir mal die Welt in der du dich versucht zu verbinden

**Comment by BreimmGer** [comment]
Super Danke schön geht
