### ISSUE TITLE
Language not changed

### ISSUE THREAD

**Issue by thomasbonsirven** [Th3C0D3R/FoBJS_Release#21]
Hello,

Impossible to chqnge lang, deutch to english not work for me. 

OS Winodws 10
![2020-04-25 15_34_14-Th3C0D3R_FoBJS_Release_ Release Repo of my private Forge of Empires Bot, written](https://user-images.githubusercontent.com/18753454/80281278-4a0cd880-870a-11ea-843c-5a92000599cd.png)
Version 1.2.3.

Im ready to help you too, for dev et language !
If you want ;)

Best regards

**Comment by Th3C0D3R** [comment]
Go to the %appdata% folder and into the "Forge of Bots Js" folder, there should be some files with one where the language is saved.
Changed this to "en" and you are good to go

**Comment by don-andruha** [comment]
As for me - I change language first and after that make Login.
When bot starts interface bacame English.

I tried to find how to set default language in config, but not found how to do it.

**Comment by thomasbonsirven** [comment]
Nice is work !

Thank You @Th3C0D3R 

@don-andruha As said @Th3C0D3R, change it in the appdata, you have a file here: %appdata%\Forge of Bots JS\Language.json

Open this file with a text editor, then between the quotes you put en

You will therefore have: "en"

Best regards

**Comment by don-andruha** [comment]
@thomasbonsirven, thanks a lot!

**Comment by thomasbonsirven** [comment]
Your welcome :)
