### ISSUE TITLE
Run on Linux

### ISSUE THREAD

**Issue by don-andruha** [Th3C0D3R/FoBJS_Release#22]
First of all I would like to thank you for your bot.
It helps me a lot!

I wait for instruction how to run it on Linux distributions.
If you do not have much time to write global instruction maybe you write just some short text How to do it. If I receive some information, maybe I can figure it out myself.

**P.S.** I understand that it's not you main project, but maybe you can say when Recurring-Quest bot (for Cultural Settlement) will be available ?
It'll be very helpful for all!

**Comment by Th3C0D3R** [comment]
Make the linux file named "fobjs" executable with chmod and execute it like ./fobjs (I think)

Also Recurring Quests has nothing to do with the settlements.

**Comment by Th3C0D3R** [comment]
Did it worked?

**Comment by don-andruha** [comment]
> Did it worked?

Sadly no. Got error:
`fobjs: 5: fobjs: Syntax error: Unterminated quoted string`

**Comment by TemhAAhmeT** [comment]
> 
> 
> > Did it worked?
> 
> Yes. It works!
> Thanks a lot!

Hi, Do you get any error when production bot is on at your linux?

**Comment by BreimmGer** [comment]
Yes 😥

**Comment by don-andruha** [comment]
> > > Did it worked?
> > 
> > 
> > Yes. It works!
> > Thanks a lot!
> 
> Hi, Do you get any error when production bot is on at your linux?

I haven`t any errors with production bot, but author [wrote](https://github.com/Th3C0D3R/FoBJS_Release/issues/23#issuecomment-619739347) in #23:
> Deactivate the Production Bot, its buggy and not usable
