### ISSUE TITLE
Auto refresh between 1 to 3sec

### ISSUE THREAD

**Issue by thomasbonsirven** [Th3C0D3R/FoBJS_Release#23]
Hello,

Ok, after change language, the windows (page) refresh is too important. Evry 2sec on average.

Possible to change this ?

**Comment by thomasbonsirven** [comment]
Look this video !
https://youtu.be/T49gQHdNa4k

**Comment by Th3C0D3R** [comment]
Deactivate the Production Bot, its buggy and not usable

**Comment by thomasbonsirven** [comment]
ok thanks.
