### ISSUE TITLE
Following exception was thrown : cannot read property "then" of undefined

### ISSUE THREAD

**Issue by miszczacha** [Th3C0D3R/FoBJS_Release#28]
Like in tittle Exeption occured :
Following exception was thrown : cannot read property "then" of undefined
arrow to -> Quit 
it shows after finishing production

**Comment by Th3C0D3R** [comment]
Is the production bot activated?

**Comment by Th3C0D3R** [comment]
please dont use the production bot. its not working perfectly and I dont know what will happen if there are to many errors (on InnoGames side e.g Bans)
