### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by TemhAAhmeT** [Th3C0D3R/FoBJS_Release#31]
Hi,

I have uploaded ForgeHX and created pull request as you have requested before.

With the update but stucks "Loading Bot..." screen.

I hope you can create time to fix it.

Cheers

**Comment by TemhAAhmeT** [comment]
`(node:7776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of null
    at D:\Downloads\fobjs_windows\fobjs-win32-x64\resources\app\main.js:430:83
(node:7776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of null
    at D:\Downloads\fobjs_windows\fobjs-win32-x64\resources\app\main.js:430:83
(node:7776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Th3C0D3R** [comment]
its fixed, please update :)
