### ISSUE TITLE
Hallo Th3C0D3R 

### ISSUE THREAD

**Issue by BreimmGer** [Th3C0D3R/FoBJS_Release#32]
Hast du den Bot Deaktiviert 
Wenn ja schade bei mir ginge es so 

Gruß Breimm

**Comment by Th3C0D3R** [comment]
Ne, ich hab ihn nicht deaktiviert, wieso?
Ich glaub mit Version 1.778 wurde nochmal was geändert was den bot kaputt gemacht hat. Muss erst nochmal ein "update" rausbringenden

**Comment by BreimmGer** [comment]
Hallo
Da er sich seit heute 18 Uhr nicht mehr einloggt

**Comment by Th3C0D3R** [comment]
einmal update ziehen, sollte behoben sein :D

**Comment by danielfelipesartorio** [comment]
Thank you for the update, for me it fixed the problem (y)
