### ISSUE TITLE
Unable to start file, think there's been an update

### ISSUE THREAD

**Issue by andrewcharlwood** [Th3C0D3R/FoBJS_Release#34]
Hey,

Was working fine until mid day today, think there may have been an update? I'm not sure.

Have tried clearing the files from /roaming/ & deleting the folder with fobjs in, and same error comes up.
![error](https://user-images.githubusercontent.com/44037977/83356679-911c6800-a35f-11ea-9ed4-87a44094afaf.JPG)

**Comment by TemhAAhmeT** [comment]
Deleting, 
**".\Roaming\Forge of Bots JS"** that folder 
and also **".\Roaming\ForgeHX-xxx.js"** helped.

**Comment by andrewcharlwood** [comment]
> Deleting,
> **".\Roaming\Forge of Bots JS"** that folder
> and also **".\Roaming\ForgeHX-xxx.js"** helped.

Forgot about the folder! Worked a treat, thank you.
