### ISSUE TITLE
Little help for the development of a new bot in another language

### ISSUE THREAD

**Issue by Dadoudu64** [Th3C0D3R/FoBJS_Release#35]
I am French and I know fairly well the programming languages .NET, C ++, Objective-C, Python, java and javascript.
So if you need help developing a new bot, I'm the man for you.

                                                                        END
                                             (I hope my English is not that bad)

**Comment by Th3C0D3R** [comment]
https://github.com/Th3C0D3R/FoBJS/

have fun ;) will accept PR if they are tested and working or new features
