### ISSUE TITLE
Bot stucks at loading screen!

### ISSUE THREAD

**Issue by TemhAAhmeT** [Th3C0D3R/FoBJS_Release#36]
Caching ForgeHX-27838551.js
ForgeHX-2783855.js cached
Loading Bot...

Bot stucks at loading after new update.

[ForgeHX-27838551.zip](https://github.com/Th3C0D3R/FoBJS_Release/files/4878594/ForgeHX-27838551.zip)

I hope you have time for a fix.

Cheers

**Comment by andrewcharlwood** [comment]
Same problem here, tried the usual clearing folder & forge files in the roaming folder

**Comment by danielfelipesartorio** [comment]
Same here :/

**Comment by danielfelipesartorio** [comment]
@Th3C0D3R maybe it's time to make the source code available. We can help fix this kind of issues

**Comment by danielfelipesartorio** [comment]
I'm still having the problem. It caches  the ForgeHX-b56af3c7, then it sucessfully logs (i get logout from other open instances), but it stucks at "Loading bot..."

**Comment by Th3C0D3R** [comment]
strange.... delete the ForgeHX and the foler called "Forge of Bots JS" inside the Roaming folder inside the appdata folder because for me its working before and after that

**Comment by BreimmGer** [comment]
Hello
who could please help me to set up bot with the new version.

thank you
