### ISSUE TITLE
Nur schwarz

### ISSUE THREAD

**Issue by felixyo** [Th3C0D3R/FoBJS_Release#4]
Hey wollte mir gestern mal deinen Bot anschauen und hab Ihn schnell gedownloaded. 
Ich weiß nicht genau was Ich falsch mache, aber er reagiert jedes mal nach dem öffnen anders. 
Nachdem Ich " Login " eingebe, passiert manchmal gar nichts ( bleibt einfach nur alles schwarz ), manchmal komme Ich wirklich zum Login. Wenn Ich mich dann eingeloggt habe, dauert es ca. 1 Minute bis Ich zur Welt Auswahl komme, wenn Ich dann de6 wähle, passiert wieder gar nichts. Dann muss Ich wieder alle Settings resetten und es geht wieder von vorne los. 
Habe Windows 10, Server de6, Konsole bleibt nach Login oder Welt Auswahl schwarz.

**Comment by Th3C0D3R** [comment]
Für die exe mal im cmd Fenster aus, dann sollte beim Login paar infos dort erscheinen. Das hier dann bitte mal posten, danke

**Comment by felixyo** [comment]
> Für die exe mal im cmd Fenster aus, dann sollte beim Login paar infos dort erscheinen. Das hier dann bitte mal posten, danke

Here you go https://i.imgur.com/RmQxLvH.png

**Comment by Th3C0D3R** [comment]
1. Öffne das Programm
2. Unter Einstellungen (Settings) "Clear userdata" und "clear everything" ausführen (nach "clear everything"  wird die Serverauswahl wieder angezeigt.
3. Bot schließen, (schau das kein Prozess mehr läuft die "fobjs.exe" oder "electron.exe" heißen) in den %appdata% Ordner gehen und die ForgeHX-xxx.js löschen wenn sie existiert und den kompletten "Forge of Bots JS" Ordner löschen
4. Bot wirder öffnen (über das CMD fenster) udn wieder "Clear userdata" und "clear everything" ausführen
5. server auswählen (de)
6. Login klicken oder in das eingabefehld eingeben.
7. Eventuell bisschen warten

wenn nach 5 Minuten nichts passiert ist, einmal die Ausgabe des CMD Fenster nochmal posten.

**Comment by felixyo** [comment]
Habe alles gemacht was du geschrieben hast. Ergebnis nach 5 Minuten:
https://i.imgur.com/NSaaPKR.png

**Comment by Th3C0D3R** [comment]
Bitte einmal neue version downloaden und alte version löschen. Auch den Ordner im Appdata Ordner. Dann nochmal den ganzen output bitte 🙈 anders kann ich grad nicht helfen

**Comment by felixyo** [comment]
Haha will dir auch eigentlich gar nicht unnötig Arbeit machen. 
Habe noch mal alles gecleared und mit der neuen Version probiert. 
Das ist das Ergebnis: https://i.imgur.com/6fh59s3.png

Frage mich jedoch woher er die Login Daten nimmt? Habe doch alles gelöscht / gecleart.

**Comment by Th3C0D3R** [comment]
Genau das ist das problem das ich nicht verstehe 😂
ich muss das heut mal in ruhe durchschauen, vielleicht hab ich einfach nur ein abfragefehler drin.

**Comment by Th3C0D3R** [comment]
Sollte mit v1.2.2 behoben sein bitte testen 😊

**Comment by felixyo** [comment]
Funktioniert jetzt super! Danke dir auf jeden Fall. Hast du Discord by any chance? Würde mich freuen mal mit dir zu quatschen. :)
LG

**Comment by Th3C0D3R** [comment]
Ja discord hab ich, aber quatschen wird schwer, bin entweder arbeiten (dann arbeite ich auch hier dran) oder zuhause und da ist dann Familienzeit (bin Vater) 😅

**Comment by felixyo** [comment]
Alles klar kein Stress. Soweit scheint alles zu funktionieren, jedoch muss Ich die Produktionen immer manuell einsammeln und dann kommt so ein Error in der Konsole: https://i.imgur.com/9RIhJHh.png
Neustarten tut er aber alles automatisch.

**Comment by Th3C0D3R** [comment]
Oh ja das ist noch ein Überbleibsel von meiner Testerei . Damit die Fehler nicht kommen einfach den Bot ausschalten (aktuell standardmäßig an) Der Produktionsbot funktioniert leider noch nicht mehr wie gewünscht (aufgrund der CPU Auslastung die ich zu begin hatte), sollte aber morgen gefixt sein, hab schon paar Ansätze.

**Comment by Th3C0D3R** [comment]
Soo funktioniert jetzt einwandfrei (hoffentlich)
