### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by leo899** [Th3C0D3R/FoBJS_Release#40]
Hello. Еell me what's wrong? 
![fob](https://user-images.githubusercontent.com/68056797/90187650-c9f6a580-ddc2-11ea-8ec2-78c75c225193.jpg)

**Comment by Th3C0D3R** [comment]
Are you running the compiled exe or the source?
Please try to delete everything inside the "AppData/Roaming/ForgeOfBots/" folder and the ForgeHX-....js file in the "Appdata/Roaming" folder if present.

**Comment by leo899** [comment]
And compiled exe and source I run, error. Cleaning everything does not helpAnd so and so I run, error. Cleaning everything does not help
