### ISSUE TITLE
Error Version / Check version not good

### ISSUE THREAD

**Issue by thomasbonsirven** [Th3C0D3R/FoBJS_Release#41]
Hello,

I have a problem, i download the last version in 1.2.6, but after start, i have a error, i need the lastest version 1.2.8, not aviable in github .. Please help  :) 
![image](https://user-images.githubusercontent.com/18753454/95291643-3b594e80-0870-11eb-8151-df17cd8bb6cd.png)

**Comment by Th3C0D3R** [comment]
Please go to this Repository into the Release section:
[FoBJS](https://github.com/Th3C0D3R/FoBJS)

The Button directs to the old release section
