### ISSUE TITLE
JS uncaught exeptions

### ISSUE THREAD

**Issue by allureGOT** [Th3C0D3R/FoBJS_Release#43]
Hi!
I get this uncaught exeption when i start the tool, can you help me out?

![image](https://user-images.githubusercontent.com/33218245/109188705-7ca4b900-7793-11eb-8ee6-696a7ef86c23.png)

**Comment by Th3C0D3R** [comment]
Open a Explorer window and enter %appdata% 
Delete the entire FoB JS folder (or Forge of Bots JS? Cant remember) to be safe

After that you have to login again but the problem should be fixed

**Comment by allureGOT** [comment]
That fixed it! Thanks 👯
