### ISSUE TITLE
v1.2.1 stating it's version 1.2.0, thus will not open

### ISSUE THREAD

**Issue by andrewcharlwood** [Th3C0D3R/FoBJS_Release#5]
Which Server are you playing on (de/en/beta(zz)/...) en
What OS you run Win 10 Pro
Are there any errors on the screen
No, the following is on the command prompt:

[DEBUG] Module loaded
[DEBUG] asar-Path loaded
[DEBUG] Settings loaded
[DEBUG] TimeThreshold loaded
[DEBUG] Vars loaded
[DEBUG] worlds.js loaded
[DEBUG] Userdata found
[DEBUG] Change Language to de
[DEBUG] Successfull changed Language to de
[DEBUG] Update checked - v1.2.1 available

Expected behavior: Open program window
Actual behavior: Below message box:

![error message](https://user-images.githubusercontent.com/44037977/74663931-a4327000-5194-11ea-9283-b468a2a219c5.JPG)

**Comment by Th3C0D3R** [comment]
Made a mistake, temp fixed in a second

**Comment by Th3C0D3R** [comment]
Fixed, just says 1.2.0 for now. Just ignore version number ^^

**Comment by Th3C0D3R** [comment]
Oh... i see something... maybe i fucked up more than thought... if no Productiontimer and RunningSince timer is shown then it's because i fucked up...

**Comment by Th3C0D3R** [comment]
Yes made mistake.

**Comment by Th3C0D3R** [comment]
Version 1.2.1 will be available tomorrow. Didn't pushed to github and so did not made a release-package

**Comment by Th3C0D3R** [comment]
So this version only has the advanced debug infos. Not the other features

**Comment by andrewcharlwood** [comment]
No prob! Looking forward to the next release
