### ISSUE TITLE
sauce?

### ISSUE THREAD

**Issue by Celuni** [Th3C0D3R/FoBJS_Release#7]
^

**Comment by Th3C0D3R** [comment]
No source. 
Why?
Because its simple as making a sandwich. 
Everything you need to make your own reqeusts are in the repos I've linked in the README.

Also I will make It OpenSource after finishing it or loosing interest in it

**Comment by Th3C0D3R** [comment]
I can go a step ahead and say that you could be lucky that I dont make it a Pay-To-Bot

**Comment by Celuni** [comment]
I have my own

**Comment by Celuni** [comment]
uploading only release, what a shady person

**Comment by Th3C0D3R** [comment]
4 sure, thats why you want the sauce... 
if you have your own, why not opensource yours? why not showing yours?

**Comment by Celuni** [comment]
Use github to keep track of changes, if you don't then don't do it.
We don't need to diffcheck each time you upload your lazy git
