### ISSUE TITLE
picking incidents has a very high chance of detection

### ISSUE THREAD

**Issue by Celuni** [Th3C0D3R/FoBJS_Release#9]
but is not limited to incidents, they plant honeypots by giving you a tampered js and data.
Make a fresh acc and pick only incidents, do nothing else, and keep track of the js and data they provide you.
You will be able to find the honeypot.

**Comment by Th3C0D3R** [comment]
What do you mean with tempered js and data? Can you give me an example?

Also. Why should collecting incidents have a higher detection?

**Comment by Celuni** [comment]
do you have the data which you say you could already have? no yo don't

**Comment by Th3C0D3R** [comment]
which data? what are you taking about?
